context:
  version: "1.0.0"

package:
  name: xojs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/xo/-/xo-${{ version }}.tgz
  sha256: 387361df91e5381b482dc58fbe044587c2e971b29e398a80c2f7bdf084ff88ef

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - xo --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: JavaScript/TypeScript linter (ESLint wrapper) with great defaults
  homepage: https://github.com/xojs/xo
  repository: https://github.com/xojs/xo

extra:
  recipe-maintainers:
    - danielnachun
