context:
  version: "1.0.1"

package:
  name: xojs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/xo/-/xo-${{ version }}.tgz
  sha256: 8992a710f067978395ea903713e1a0a00a6aae3360283b5206ef68ffd35d8c61

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - xo --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: JavaScript/TypeScript linter (ESLint wrapper) with great defaults
  homepage: https://github.com/xojs/xo
  repository: https://github.com/xojs/xo

extra:
  recipe-maintainers:
    - danielnachun
