context:
  version: "0.60.0"

package:
  name: xojs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/xo/-/xo-${{ version }}.tgz
  sha256: 233a00ce9d29f5a4ad38234f55ce013c6313ea7df47987aa6dd66c49b6b74121

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - xo --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: JavaScript/TypeScript linter (ESLint wrapper) with great defaults
  homepage: https://github.com/xojs/xo
  repository: https://github.com/xojs/xo

extra:
  recipe-maintainers:
    - danielnachun
