context:
  version: "1.0.3"

package:
  name: xojs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/xo/-/xo-${{ version }}.tgz
  sha256: 2cda78ed3cb129183ebdfae60037d5bda10bf2f06e2f65f75e34d487235edfe3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - xo --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: JavaScript/TypeScript linter (ESLint wrapper) with great defaults
  homepage: https://github.com/xojs/xo
  repository: https://github.com/xojs/xo

extra:
  recipe-maintainers:
    - danielnachun
